### ISSUE TITLE
Fullscreen on Smartphones

### ISSUE THREAD

**Issue by haldo98** [Elius94/psv-lens-flare-plugin#4]
### What happened?

when toggling fullscreen mode **in smartphones** the flares disappear.

check my demo page

https://www.tadini.it/temp/ps_sanfedelino.html

### What should have happened?

flares working also in fullscreen

### Code

-

### Library Version

1.0.4

### Node Version

-

### What operating system are you using?

Other

### What browser are you using?

Chrome

### Interest to fix the bug

- [ ] I would like to fix this bug!

**Comment by Elius94** [comment]
Hi! what is your smartphone? your example works on my android phone!!

**Comment by haldo98** [comment]
Xiaomi MI 11 android 12

https://user-images.githubusercontent.com/97630238/220140340-07acebe0-e370-4fca-8230-7ab7c9f9c3ae.mp4

**Comment by Elius94** [comment]
Strano! io ho un Redmi, quindi simile al tuo e funziona bene

**Comment by haldo98** [comment]
I forgot about this bug... but i checked the latest version and the bug no longer occurs...

closed as solved.
