### ISSUE TITLE
Toggle all lens Flares

### ISSUE THREAD

**Issue by haldo98** [Elius94/psv-lens-flare-plugin#5]
### What are you trying to do?

https://www.tadini.it/temp/ps_sanfedelino.html

I have a button and a keyboard action (s)  that should toggle flares with `viewer.toggleAllLensflares();`

but returns:  Uncaught TypeError: viewer.toggleAllLensflares is not a function

Maybe I did something wrong...

### Code

-

### Library Version

1.0.4

### Node Version

-

### What operating system are you using?

Windows

### What browser are you using?

Chrome

**Comment by Elius94** [comment]
Hi! You don't have to call `toggleAllLensflares` from viewer instance...
You have to get the plugin instance by using this:

```js
const lensflaresPlugin = viewer.getPlugin(LensflarePlugin)

// and so you can call the methods:
lensflaresPlugin.toggleAllLensflares()
```

But is my fault because I've written the readme wrong!
I'm gonna fix it and release a new one.

Thanks.

**Comment by haldo98** [comment]
I edited the page but still I got this error...

Uncaught ReferenceError: LensflarePlugin is not defined  in

var lensflaresPlugin = viewer.getPlugin(LensflarePlugin);

**Comment by Elius94** [comment]
```js
import { LensflarePlugin } from 'photo-sphere-viewer-lensflare-plugin';

const viewer = new Viewer({
    container: document.querySelector('#viewer') as HTMLElement,
    caption: 'test',
    plugins: [
        LensflarePlugin
    ]
});

var lensflarePlugin = viewer.getPlugin(LensflarePlugin);

```

if you use Typescript you have to specify the type:

```ts
const lensflare = viewer.getPlugin(LensflarePlugin) as LensflarePlugin;
```

Let me know

**Comment by haldo98** [comment]
esatto...  Non ho import perchè uso <script src ma il resto è uguale...

https://www.tadini.it/temp/PS_sanfedelino.html

**Comment by Elius94** [comment]
Ok, è un bug nella lib
https://codesandbox.io/s/photo-sphere-viewer-lensflare-plugin-2oz3zh?file=/src/index.js

Provo a sistemarlo, 
ad ora puoi usare 
    lf.hideLensflare("sun");

o show.

**Comment by Elius94** [comment]
Ok, rilasciato v1.1.1 in cui funzionano correttamente:
"toggleAllLensflares()"
"showAllLensflares()"
"hideAllLensflares()"

Aggiorna pure

**Comment by haldo98** [comment]
Minimized version now updated to 1.1.1 

but the error is still there  :(

**Comment by Elius94** [comment]
https://codesandbox.io/s/photo-sphere-viewer-lensflare-plugin-2oz3zh?file=/src/index.js

Did you looked at this sample?

In this sandbox every two seconds runs "toggleAllLensflares"

**Comment by haldo98** [comment]
Elia.. si ho visto...ma il problema non è toggleAllLensflares

da questa pagina ho eliminato tutto ... bottoni - keyboard actions - plugins (tranne lensflare ovviamente)  
https://www.tadini.it/temp/ps_sanfedelino.html
e non da errore....

in questa invece 

https://www.tadini.it/temp/ps_sanfedelino2.html

ho aggiunto solo   `const lensflaresPlugin = viewer.getPlugin(LensflarePlugin);`

e da errore....    senza usare nessun metodo.

l'unica differenza con la tua sandbox è che tu usi import

**Comment by Elius94** [comment]
Ok allora non vorrei che il problema sia che in caso di import da CDN HTML tu debba inserire il nome del plugin in questo modo:

```js
const lensflaresPlugin = viewer.getPlugin(PhotoSphereViewerLensflarePlugin);
```

Fammi sapere

**Comment by haldo98** [comment]
si è quello.. ora funziona tutto perfettamente.

Grazie
