### ISSUE TITLE
visibleOnLoad

### ISSUE THREAD

**Issue by haldo98** [Elius94/psv-lens-flare-plugin#6]
### What do you want?

How about the visibleOnLoad configuration   ?   (true - false)

to decide whether the flares are visible when loading the panorama

### Why do you want it?

to have the flares only visible upon request (button or keyboard action)

### How do you implement it?

..

### Are you interested in developing this feature?

- [ ] Yes, I am interested in developing this feature
- [ ] No, I am not interested in developing this feature

**Comment by Elius94** [comment]
Hi! using the plugin methods, this functionality would make sense to implement it at the application level and not at the library level. You could create the lensflares not visible at first and then make them visible in the "ready" event of the photo sphere viewer. This plugin is meant to be almost completely static in the view.
